const MESSAGE_TYPES = {
    CREATE_ROOM: 'CREATE_ROOM',
    ROOM_CREATED: 'ROOM_CREATED',
    JOIN_ROOM: 'JOIN_ROOM',
    ERROR: 'ERROR',
    ASSIGN_SYMBOL_AND_START_GAME: 'ASSIGN_SYMBOL_AND_START_GAME',
    SEND_MOVE: 'SEND_MOVE',
    RECEIVE_MOVE: 'RECEIVE_MOVE',
    KEEP_ALIVE: 'KEEP_ALIVE'
};

export default MESSAGE_TYPES;